language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 5.6
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 7.0
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 7.1
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: hhvm
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
    allow_failures:
        - php: hhvm

branches:
    only:
        - master


before_script:
    - composer global require hirak/prestissimo
    - composer update ${COMPOSER_FLAGS}

script:
    - make test
