parameters:
    knp_megaman.cache_file:          "%kernel.cache_dir%/knp_megaman_cache.json"
    knp_megaman.composer_json:       "%kernel.root_dir%/../composer.json"
    knp_megaman.documentation_file:  "README.md"
    knp_megaman.installed_json:      "%knp_megaman.vendor_dir%/composer/installed.json"
    knp_megaman.readme:              "%kernel.root_dir%/../README.md"
    knp_megaman.vendor_dir:          "%kernel.root_dir%/../vendor"

services:
    knp_megaman.cache.documentation_warmer:
        class: Knp\MegaMAN\Cache\DocumentationWarmer
        arguments:
            - %knp_megaman.cache_file%
            - %knp_megaman.documentation_file%
            - %knp_megaman.vendor_dir%
        calls:
            - ['addFilter', [@knp_megaman.filter.composer_file]]
            - ['addFilter', [@knp_megaman.filter.package_name]]
            - ['addFilter', [@knp_megaman.filter.version_installed]]
            - ['addFilter', [@knp_megaman.filter.source_url]]
            - ['addFilter', [@knp_megaman.filter.direct_dependency]]
            - ['addFilter', [@knp_megaman.filter.dev_dependency]]
            - ['addFilter', [@knp_megaman.filter.local_project]]
        tags:
            - { name: kernel.cache_warmer, priority: 0 }

    knp_megaman.controller.markdown_renderer_controller:
        class: Knp\MegaMAN\Controller\MarkdownRenderController
        calls:
            - ['addProcessor', [@knp_megaman.processor.css]]
            - ['addProcessor', [@knp_megaman.processor.relative_link]]
            - ['addProcessor', [@knp_megaman.processor.absolute_link]]

    knp_megaman.css_inliner:
        class: TijsVerkoyen\CssToInlineStyles\CssToInlineStyles

    knp_megaman.data_collector.documentation_viewer:
        class: Knp\MegaMAN\DataCollector\DocumentationViewer
        arguments:
            - %knp_megaman.cache_file%
        tags:
            - { name: data_collector, template: "MegaMANBundle::wdt.html.twig", id: "megaman" }

    knp_megaman.filter.composer_file:
        class: Knp\MegaMAN\Filter\ComposerFile

    knp_megaman.filter.dev_dependency:
        class: Knp\MegaMAN\Filter\DevDependency
        arguments:
            - %knp_megaman.composer_json%

    knp_megaman.filter.direct_dependency:
        class: Knp\MegaMAN\Filter\DirectDependency
        arguments:
            - %knp_megaman.composer_json%

    knp_megaman.filter.local_project:
        class: Knp\MegaMAN\Filter\LocalProject
        arguments:
            - %knp_megaman.readme%
            - %knp_megaman.composer_json%

    knp_megaman.filter.package_name:
        class: Knp\MegaMAN\Filter\PackageName

    knp_megaman.filter.source_url:
        class: Knp\MegaMAN\Filter\SourceUrl
        arguments:
            - %knp_megaman.installed_json%

    knp_megaman.filter.version_installed:
        class: Knp\MegaMAN\Filter\VersionInstalled
        arguments:
            - %knp_megaman.installed_json%

    knp_megaman.processor.absolute_link:
        class: Knp\MegaMAN\Markdown\Processor\AbsoluteLink

    knp_megaman.processor.css:
        class: Knp\MegaMAN\Markdown\Processor\Css
        arguments:
            - @knp_megaman.css_inliner

    knp_megaman.processor.relative_link:
        class: Knp\MegaMAN\Markdown\Processor\RelativeLink
        arguments:
            - @router
            - @request_stack
